[package]
name = "class-a"
version = "0.1.0"
authors = ["anathayna <anathaynafranca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
